### ISSUE TITLE
Admin Privileges

### ISSUE THREAD

**Issue by vimaxx** [ZeeTechUOW/cycfrontend#22]
According to spec, the admin should be able to:
1. Add/Delete/Edit users
2. Add/Delete/Edit content (post/threads/module?/certs?/scores?)

**Comment by metafalls** [comment]
I think we should just hold it to post and threads since the 3 others are not as integral...

thoughts?

**Comment by vimaxx** [comment]
sure, it's not explicitly defined in the specs, so we can have some liberty on the definition.
